export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const AUTH_LOGIN = 'AUTH_LOGIN'
export const SET_LOGIN_DATA = 'SET_LOGIN_DATA'
export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const CHECK_LOGIN = 'CHECK_LOGIN'